name: Build and Release APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  # Create a GitHub release when a tag is pushed
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download built APK
        uses: actions/download-artifact@v3
        with:
          name: app-release
          path: artifacts

      - name: Rename APK with version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          mv artifacts/app-release-unsigned.apk "artifacts/droidrun-portal-${TAG_NAME}.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.apk
          draft: false
          prerelease: false
          generate_release_notes: true